apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservice
resources:
  - namespace.yaml
  - nacos.yaml
  - user-service.yaml
  - order-service.yaml
  - gateway-server.yaml
